/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PCodeRouteImport } from './routes/p.$code'
import { Route as JourneyIdRouteImport } from './routes/journey.$id'
import { Route as AdminPatientsIdRouteImport } from './routes/admin_.patients.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PCodeRoute = PCodeRouteImport.update({
  id: '/p/$code',
  path: '/p/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyIdRoute = JourneyIdRouteImport.update({
  id: '/journey/$id',
  path: '/journey/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPatientsIdRoute = AdminPatientsIdRouteImport.update({
  id: '/admin_/patients/$id',
  path: '/admin/patients/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/journey/$id': typeof JourneyIdRoute
  '/p/$code': typeof PCodeRoute
  '/admin/patients/$id': typeof AdminPatientsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/journey/$id': typeof JourneyIdRoute
  '/p/$code': typeof PCodeRoute
  '/admin/patients/$id': typeof AdminPatientsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/journey/$id': typeof JourneyIdRoute
  '/p/$code': typeof PCodeRoute
  '/admin_/patients/$id': typeof AdminPatientsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/journey/$id'
    | '/p/$code'
    | '/admin/patients/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/journey/$id'
    | '/p/$code'
    | '/admin/patients/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/journey/$id'
    | '/p/$code'
    | '/admin_/patients/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  JourneyIdRoute: typeof JourneyIdRoute
  PCodeRoute: typeof PCodeRoute
  AdminPatientsIdRoute: typeof AdminPatientsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$code': {
      id: '/p/$code'
      path: '/p/$code'
      fullPath: '/p/$code'
      preLoaderRoute: typeof PCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/$id': {
      id: '/journey/$id'
      path: '/journey/$id'
      fullPath: '/journey/$id'
      preLoaderRoute: typeof JourneyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/patients/$id': {
      id: '/admin_/patients/$id'
      path: '/admin/patients/$id'
      fullPath: '/admin/patients/$id'
      preLoaderRoute: typeof AdminPatientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  JourneyIdRoute: JourneyIdRoute,
  PCodeRoute: PCodeRoute,
  AdminPatientsIdRoute: AdminPatientsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
